export const data = [
  {
    id: 1,
    name: "ADA",
    slug: "ada",
    // cover: require("../../assets/videos/ada.jpg"),
    coverVideo: require("../../assets/videos/ada.mp4"),
    coverVideoType: "video/mp4",
    primaryColor: "#25252c",
    isWide: false,
  },
  {
    id: 2,
    name: "IID",
    slug: "ada",
    // cover: require("../../assets/videos/iid.jpg"),
    coverVideo: require("../../assets/videos/iid.mp4"),
    coverVideoType: "video/mp4",
    primaryColor: "#efcc16",
    isWide: false,
  },
  {
    id: 3,
    name: "Everest",
    slug: "ada",
    // cover: require("../../assets/videos/everest.jpg"),
    coverVideo: require("../../assets/videos/everest.mp4"),
    coverVideoType: "video/mp4",
    primaryColor: "#2b5f71",
    isWide: true,
  },
  {
    id: 4,
    name: "Microsoft",
    slug: "ada",
    // cover: require("../../assets/videos/ms.jpg"),
    coverVideo: require("../../assets/videos/ms.mp4"),
    coverVideoType: "video/mp4",
    primaryColor: "#2976d4",
    isWide: false,
  },
  {
    id: 5,
    name: "OA",
    slug: "ada",
    // cover: require("../../assets/videos/oa.jpg"),
    coverVideo: require("../../assets/videos/oa.mp4"),
    coverVideoType: "video/mp4",
    primaryColor: "#337578",
    isWide: false,
  },
]
