export const data = [
  {
    id: 1,
    name: "Ada",
    slug: "ada",
    // cover: require("../../assets/videos/ada.jpg"),
    coverVideo: require("../../assets/videos/ada.mp4"),
    coverVideoType: "video/mp4",
    primaryColor: "#242326",
    isInverseColor: true,
    isWide: false,
  },
  {
    id: 2,
    name: "印印，自己来",
    slug: "ada",
    // cover: require("../../assets/videos/iid.jpg"),
    coverVideo: require("../../assets/videos/iid.mp4"),
    coverVideoType: "video/mp4",
    primaryColor: "#f0d219",
    isInverseColor: false,
    isWide: false,
  },
  {
    id: 3,
    name: "Everest Financial Group",
    slug: "ada",
    // cover: require("../../assets/videos/everest.jpg"),
    coverVideo: require("../../assets/videos/everest.mp4"),
    coverVideoType: "video/mp4",
    primaryColor: "#2a5f6f",
    isInverseColor: true,
    isWide: true,
  },
  {
    id: 4,
    name: "Microsoft Service Hub",
    slug: "ada",
    // cover: require("../../assets/videos/ms.jpg"),
    coverVideo: require("../../assets/videos/ms.mp4"),
    coverVideoType: "video/mp4",
    primaryColor: "#257fd8",
    isInverseColor: true,
    isWide: false,
  },
  {
    id: 5,
    name: "办公管理平台",
    slug: "ada",
    // cover: require("../../assets/videos/oa.jpg"),
    coverVideo: require("../../assets/videos/oa.mp4"),
    coverVideoType: "video/mp4",
    primaryColor: "#397e80",
    isInverseColor: true,
    isWide: false,
  },
]
